version: '3'
services:
    ac-db:
        image: postgres:12
        ports: 
          - 5432:5432
        environment:
          PGDATA: /var/lib/pgsql/data/
          POSTGRES_PASSWORD: pass
        volumes:
          - "./ac_db-init/:/docker-entrypoint-initdb.d/"
          - "/tmp/db:/var/lib/pgsql/data/"
        restart: unless-stopped

    ac-api:
        image: git.disoft.us:5050/nastya/ac-back:basic
        command: >
            bash -c "python3 manage.py migrate && python3 manage.py loaddata pon/fixtures/models_data.json &&  python3 manage.py runserver 0.0.0.0:9191"
        environment:
          WAIT_HOSTS: ac-db:5432
        ports: 
          - 9191:9191
        volumes:
          - "../:/usr/ac-back/"
        depends_on:
          - ac-db
        restart: unless-stopped

